source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.1'

use_frameworks!

xcodeproj 'DrugChart'

pod 'AFNetworking', '~> 2.6.1'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'Fabric', '~> 1.5.5'
pod 'Crashlytics', '~> 3.3.4'
pod 'CocoaLumberjack/Swift'